Name = ""

# Supports markdown
About = ""

# Add only the handle
Github = ""
Twitter = ""

# Add the absolute links
Goodreads = ""
Linkedin = ""

Email = ""

# Add the filename with file extension.
Resume = ""

# Sets the number of posts to display on the front page
PostLimit = 4